apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-artifacts-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
