apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inedo-sql
spec:
  serviceName: "inedo-sql"
  replicas: 1
  selector:
    matchLabels:
      app: inedo-sql
  template:
    metadata:
      labels:
        app: inedo-sql
    spec:
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsGroup: 10001
        runAsNonRoot: true

      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
          name: sql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: sa-password
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
