apiVersion: apps/v1
kind: Deployment
metadata:
  name: otter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otter
  template:
    metadata:
      labels:
        app: otter
    spec:
      containers:
      - name: otter
        image: proget.inedo.com/productimages/inedo/otter:latest
        ports:
        - containerPort: 80
        env:
        - name: OTTER_SQL_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: inedo-config-otter
              key: OTTER_SQL_CONNECTION_STRING
        
 
---
apiVersion: v1
kind: Service
metadata:
  name: otter
spec:
  selector:
    app: otter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
